CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(255) DEFAULT '默认头像.png' COMMENT '头像URL',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT='用户表';


CREATE TABLE IF NOT EXISTS `post` (
  `post_id` INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` INTEGER UNSIGNED NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `cover_image` VARCHAR(500) COMMENT '封面图',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='帖子表';


CREATE TABLE IF NOT EXISTS `comment` (
  `comment_id` INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `post_id` INTEGER UNSIGNED NOT NULL,
  `user_id` INTEGER UNSIGNED NOT NULL,
  `content` TEXT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT='评论表';

CREATE TABLE IF NOT EXISTS `user_details` (
  `user_id` INTEGER UNSIGNED NOT NULL PRIMARY KEY COMMENT '用户ID',
  `phone` VARCHAR(11) UNIQUE COMMENT '手机号',
  `email` VARCHAR(100) UNIQUE COMMENT '邮箱',
  `gender` TINYINT DEFAULT 0 COMMENT '性别：0-未知 1-男 2-女',
  `bio` VARCHAR(255) COMMENT '个人简介',
  `follow_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '关注数',
  `fans_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '粉丝数',
  `post_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '发布帖子数',
  `like_receive_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '获赞总数',
  `status` TINYINT DEFAULT 1 COMMENT '状态：0-禁用 1-正常',
  -- `last_login_time` DATETIME COMMENT '最后登录时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='用户详情表';

CREATE TABLE IF NOT EXISTS `post_details` (
  `post_id` INTEGER UNSIGNED PRIMARY KEY COMMENT '帖子ID',
  `type` TINYINT DEFAULT 3 COMMENT '类型：1-图文 2-视频 3-纯文字',
  `topic_ids` VARCHAR(255) COMMENT '关联话题ID，多个用逗号分隔',
  `view_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '浏览量',
  `like_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '点赞数',
  `comment_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '评论数',
  `collect_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '收藏数'
  -- `status` TINYINT DEFAULT 1 COMMENT '状态：0-待审核 1-已发布 2-审核不通过 3-已删除',
  -- `audit_remark` VARCHAR(255) COMMENT '审核备注',
  -- `audit_time` DATETIME COMMENT '审核时间',
) COMMENT='帖子详情表';

CREATE TABLE IF NOT EXISTS`post_image` (
  `post_image_id` INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `post_id` INTEGER UNSIGNED NOT NULL COMMENT '帖子ID',
  `url` VARCHAR(500) NOT NULL COMMENT '图片URL',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP
) COMMENT='帖子图片表';

CREATE TABLE IF NOT EXISTS `topic` (
  `topic_id` INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '话题ID',
  `topic_name` VARCHAR(50) NOT NULL COMMENT '话题名称',
  `topic_description` VARCHAR(200) COMMENT '话题描述',
  `topic_icon` VARCHAR(500) COMMENT '话题图标',
  `cover` VARCHAR(500) COMMENT '话题封面',
  `post_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '帖子数',
  `follow_count` INTEGER UNSIGNED DEFAULT 0 COMMENT '关注数',
  `is_hot` TINYINT DEFAULT 0 COMMENT '是否热门',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP
) COMMENT='话题表';

CREATE TABLE IF NOT EXISTS `post_topic` (
  `post_topic_id` INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `post_id` INTEGER UNSIGNED NOT NULL,
  `topic_id` INTEGER UNSIGNED NOT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `uk_post_topic` UNIQUE (`post_id`, `topic_id`)
) COMMENT='帖子话题关联表';

CREATE TABLE IF NOT EXISTS `follow` (
  `follow_id` INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `follower_id` INTEGER UNSIGNED NOT NULL COMMENT '关注者ID（粉丝）',
  `following_id` INTEGER UNSIGNED NOT NULL COMMENT '被关注者ID（博主）',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `uk_follower_following` UNIQUE (`follower_id`, `following_id`)
) COMMENT='关注表';

CREATE TABLE IF NOT EXISTS `like` (
  `like_id` INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` INTEGER UNSIGNED NOT NULL,
  `post_id` INTEGER UNSIGNED NOT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `uk_user_post` UNIQUE (`user_id`, `post_id`)
)COMMENT='点赞表';
