CREATE TABLE IF NOT EXISTS `user` (
	`user_id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(20) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL,
	`avatar` VARCHAR(255) NOT NULL,
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`user_id`)
) COMMENT='用户表';


CREATE TABLE IF NOT EXISTS `post` (
	`post_id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INTEGER UNSIGNED NOT NULL,
	`title` VARCHAR(50) NOT NULL,
	`content` MEDIUMTEXT NOT NULL,
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`post_id`)
) COMMENT='帖子表';


CREATE TABLE IF NOT EXISTS `comment` (
	`comment_id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`post_id` INTEGER UNSIGNED NOT NULL,
	`user_id` INTEGER UNSIGNED NOT NULL,
	`content` TEXT NOT NULL,
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`comment_id`)
) COMMENT='评论表';
